global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "kafka-alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Kafka Exporter - Kafka cluster metrics
  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']
    scrape_interval: 30s

  # Kafka JMX metrics
  - job_name: 'kafka-jmx'
    static_configs:
      - targets: ['jmx-kafka:5556']
    scrape_interval: 30s

  # Schema Registry JMX metrics
  - job_name: 'schema-registry-jmx'
    static_configs:
      - targets: ['jmx-schema-registry:5556']
    scrape_interval: 30s

  # Zookeeper JMX metrics
  - job_name: 'zookeeper-jmx'
    static_configs:
      - targets: ['jmx-zookeeper:5556']
    scrape_interval: 30s

  # Node/System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']